config/routes.rb
Blog::Application.routes.draw do
  get "ref/index"

  get "marklet/index"
  get "marklet/capture"

  get "home/index"
  get "home/bubblezoo"
  get "/home/page"
  match "/home/page/:page", :to => redirect("/home/page?page=%{page}")
  

  get "qr/index"
  post "qr/generate"
  
  get "dns/index"
  post "dns/available"

  resources :posts do
    resources :comments
  end
  

  get "tumble/index"
  match "/tumble/page/:page", :to => redirect("/home/page?page=%{page}")
  get "tumble/flickr"
  
  match "/auth/:provider/callback" => "sessions#create"
  match "/signout" => "sessions#destroy", :as => :signout

  root :to => 'home#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :name, :presence => true
  validates :title, :presence => true,
            :length => { :minimum => 5 }

  has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["name"]
    end
  end
end

app/controllers/dns_controller.rb
require 'combinator'
require 'dns_trawler'

class DnsController < ApplicationController

  def index

  end
  

  def available
    names = params[:dnsnames]
    combinator = Combinator.new
    
    unless(params[:prefix].nil?) 
      names = combinator.add_prefix(params[:prefix], names.split).join " "
    end
    unless(params[:suffix].nil?) 
        names = combinator.add_suffix(params[:suffix], names.split).join " "
    end
    
    @io = DnsTrawler.new.find_available names, params[:tld]
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    #reset_session
  end
  
  def page
    
  end
  
  def bubblezoo
    #render_component '/photos/page'
  end
  
  
end

app/controllers/marklet_controller.rb
class MarkletController < ApplicationController
  def options
      render :nothing => true, :status => 204
      response.headers['Access-Control-Allow-Origin'] = '*'
      response.headers['Access-Control-Allow-Methods'] = 'POST, GET, PUT, DELETE, OPTIONS'
      response.headers['Access-Control-Allow-Credentials'] = 'true'
      response.headers['Access-Control-Max-Age'] = '86400' # 24 hours
      response.headers['Access-Control-Allow-Headers'] = 'X-Requested-With, X-HTTP-Method-Override, Content-Type, Accept'
    end

  
  
  def index
    unless ([80, 443].include? request.port) 
      @url_base = "http://#{request.host}:#{request.port}"
    end
    @url_base ||= "http://#{request.host}"
  end
  def capture
    @text = params[:text] || "Text not sent."
    @url = params[:source] || "Source not sent."
    render :layout => 'marklet_uber' 
  end
end

app/controllers/posts_controller.rb
# module Tweet
#   def tweet(message)
#     client = Twitter.client
#     client.update(message)
#     "Message was tweeted."
#   rescue Exception => e
#     "Message was not tweeted due to an error: #{/\s\d{3}\s.*/.match(e)}"
#   end
# end

class PostsController < ApplicationController
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        response = tweet("A new post is available: '##{@post.id} #{@post.title}'   http://noolog.com/posts/#{@post.id}")
        format.html { redirect_to @post, notice: "Post was successfully created. #{response}." }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update

    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :ok }
    end
  end
end

app/controllers/qr_controller.rb
class QrController < ApplicationController
  def index
    
  end

  def generate
    
  end

end

app/controllers/ref_controller.rb
class RefController < ApplicationController
  def index
  end
end

app/controllers/tumble_controller.rb
class TumbleController < ApplicationController
  def index
    session[:per_page] = 3 if session[:per_page].nil?
    # session[:per_page] += 1
  end
  
  def page
    redirect_to :controller => 'home', :action => 'page'
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dns_helper.rb
module DnsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/marklet_helper.rb
module MarkletHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/qr_helper.rb
module QrHelper
end

app/helpers/ref_helper.rb
module RefHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tumble_helper.rb
module TumbleHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html lang="en">
	<head>
		<title>
			NooLog
		</title><%= stylesheet_link_tag "application" %><%= javascript_include_tag "application" %><%= csrf_meta_tags %>
		<%= javascript_include_tag "jquery.infinitescroll.js" %>
		

	  
	
	</head>
	<body>
		

	
			
			<div id="header">
			 <!-- <%= image_tag("Vector_Banner_000145.jpg", :border=>0, :style => "float: left;") %> -->
			
			 
			 <div id="user_nav" style="padding-right: 20px; float: right;">
				<div style="float: right">
					<span><%= link_to "Home", "/" %></span>
					<span> | </span>
					<span><%= link_to "Bubbles", "/home/bubblezoo" %></span>
					<span> | </span>
					<span><%= link_to "Tumble Log", "/tumble/index" %></span>
					<span> | </span>
					<span><%= link_to "Marklet", "/marklet/index" %></span>
					<span> | </span>
					<span><%= link_to "Reference", "/ref/index" %></span>
					<span> | </span>
					<span><%= link_to "QR Generator", "/qr/index" %></span>
					<span> | </span>
					<span><%= link_to "DNS Trawler", "/dns/index" %></span>
					<span> | </span>
					<span><%= link_to "Blog", posts_path %></span>
					<span> | </span>
					<span><% if current_user %> Welcome <%= current_user.name %>! <%= link_to "Sign Out", signout_path %> <% else %> <%= link_to "Sign in with Twitter", "/auth/twitter" %> <% end %></span>
				</div>
			 </div>
			 <div style="clear: both"></div>
			</div>
			
			<div style="height: 10px"></div>	
				
		
			<div id="wrapper">
				
				
				
				<div style="clear: both"></div>
				
				
				
				
				
					<div id="container" class="transitions-enabled infinite-scroll has-gutters clearfix" style="margin-left: 60px; margin-right: 60px; padding: 5px 5px 5px 5px; border: 1px solid #AAAAAA;">
						
						
						
						<div><%=h yield %></div>
					</div>
					<div id="sidebar">
						
					</div>
			</div>
			<div class="footer">
        	 	<div style="display: float-left">Copyright (c) 2012</div>
				<div style="display: float-left">Blog @<a href="http://uberpwn.wordpress.com">Wordpress</div>	
					<div id="social-container" style="float: left">
						<a href="https://twitter.com/jclosure" class="twitter-follow-button" data-show-count="false" data-size="large">Follow @jclosure</a> <script type="text/javascript">
	!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");
						</script>
					</div>
					<div style="float: right"></div>
					<div style="clear: both"></div>
	        </div>

	</body>
</html>

app/views/layouts/marklet_uber.html.erb
<!DOCTYPE html>

<html lang="en">
<head>
	<%= javascript_include_tag "application" %>
	<%= stylesheet_link_tag params[:controller] %>
	<%= javascript_include_tag params[:controller] %>
	
	
</head>

<body id="container">
	<%=h yield %>
</body>

</html>